# Generated by Django 5.0.1 on 2024-02-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_alter_patient_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertwo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
