# Generated by Django 5.0.1 on 2024-02-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('experience', models.IntegerField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.FileField(upload_to=''),
        ),
    ]
