# Generated by Django 5.0.1 on 2024-02-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0008_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(default='male', max_length=200),
            preserve_default=False,
        ),
    ]
