# Generated by Django 5.0.1 on 2024-02-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0009_staff_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=200)),
                ('stock', models.IntegerField(max_length=200)),
                ('expiryDate', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
            ],
        ),
    ]
