# Generated by Django 5.0.1 on 2024-02-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0011_bed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='admissionDate',
            new_name='allotmentDate',
        ),
    ]
