# Generated by Django 5.0.1 on 2024-02-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0013_alter_bed_roomtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='roomtype',
            new_name='roomType',
        ),
    ]
