# Generated by Django 5.0.1 on 2024-02-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0015_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bill',
            field=models.FileField(default='file', upload_to=''),
            preserve_default=False,
        ),
    ]
